[package]
name = "hugr-qir"
version = "0.2.0-rc.1"
edition = "2024"
rust-version = "1.91"

[features]
default = ["py"]
py = ["dep:pyo3"]

[dependencies]
anyhow = "1.0"
clap = "4.6"
clap-verbosity-flag = "3.0"
clio = { version = "0.3.5", features = ["clap-parse"] }
hugr = { version = "0.27", features = ["llvm"] }
hugr-cli = "0.27"
hugr-core = "0.29"
hugr-llvm = { version = "0.27", features = ["test-utils"] }
itertools = "0.15.0"
lazy_static = "1.5.0"
pyo3 = { version = "0.29", features = [
    "abi3-py310",
    "anyhow",
], optional = true }
serde = "1.0"
# this needs to match the version used by tket so we can implement its traits.
strum = "0.28.0"
tket = "0.18.0"
tket-qsystem = { version = "0.24.0", features = ["cli"] }
wasmparser = { version = "0.252", default-features = false }

[dev-dependencies]
insta = "1.47"
rstest = "0.26.1"
serde = { version = "1.0", features = ["derive"] }
typetag = "0.2"
