[package]
name = "hugr-qir"
version = "0.0.28"
edition = "2024"
rust-version = "1.89"

[features]
default = ["py"]
py = ["dep:pyo3"]

[dependencies]
anyhow = "1.0"
clap = "4.6"
clap-verbosity-flag = "3.0"
clio = { version = "0.3.5", features = ["clap-parse"] }
hugr = { version = "0.25.6", features = ["llvm"] }
hugr-cli = "0.25.6"
hugr-core = "0.25.7"
hugr-llvm = { version = "0.25.7", features = ["test-utils"] }
inkwell = { version = "0.8.0", features = ["llvm14-0"] }
itertools = "0.14.0"
lazy_static = "1.5.0"
pyo3 = { version = "0.28", features = [
    "abi3-py310",
    "anyhow",
], optional = true }
serde = "1.0"
tket = "0.17.0"
tket-qsystem = { version = "0.23.0", features = ["cli"] }
wasmparser = { version = "0.248", default-features = false }

[dev-dependencies]
insta = "1.47"
rstest = "0.26.1"
serde = { version = "1.0", features = ["derive"] }
typetag = "0.2"
