[project]
name = "hugr-qir"
dynamic = ["version"]
description = "Quantinuum's tool for converting HUGR to QIR"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.3.1,<8.5.0",
    "guppylang>=1.0.1,<2.0.0",
    "hugr>=0.18.3",
    "pytket>=2.4.0",  # we only use BackendResult, this is the last version where it changed
    "quantinuum-qircheck~=0.8.0",
]

[project.scripts]
hugr-qir = "hugr_qir.cli:hugr_qir"

[dependency-groups]
dev = [
    "guppylang-internals>=1.0.1,<2.0.0",
    "maturin>=1.11.5,<2.0",
    "pytest-cov>=7.0.0,<8",
    "pytest-mock>=3.15.1",
    "pytest-snapshot>=0.9.0",
    "pytest-xdist>=3.8.0",
    "pytest>=9.0.2",
    "ruff>=0.15.0",
    "ty>=0.0.34",
]
docs = [
    "enum-tools[sphinx]>=0.13.0",
    "myst-nb>=1.2.0",
    "quantinuum-sphinx~=0.6",
    "sphinx>=8,<9",
    "sphinx-autodoc-typehints<3.2",
    "sphinx-copybutton>=0.5.2,<1",
    "sphinxcontrib-googleanalytics>=0.5",
    "sphinx-click>=6.2.0"
]
examples = [
    "jupyterlab>=4.5.3",
    "qnexus~=0.48.0",
]

[build-system]
requires = ["maturin>=1.4,<2.0"]
build-backend = "maturin"

[tool.uv]
# rebuild package when Rust source changes
cache-keys = [
    { file = "Cargo.toml" },
    { file = "Cargo.lock" },
    { file = "src/**/*.rs" },
]

[tool.ty.analysis]
replace-imports-with-any = ["qnexus", "qnexus.**"]

[tool.ty.src]
include = ["python"]

[tool.ty.terminal]
error-on-warning = true

[tool.ty.environment]
python-version = "3.12"

[tool.deptry]
known_first_party = ["hugr_qir"]

[tool.deptry.per_rule_ignores]
DEP001 = ["tests"]
DEP004 = [
    "guppylang_internals", # used in tests and examples
    "pytest_snapshot",     # used in tests
    "pytest",              # used in tests
    "qnexus",              # used in examples
]

[tool.maturin]
features = ["pyo3/extension-module"]
module-name = "hugr_qir._hugr_qir"
python-source = "python/"
python-packages = ["hugr_qir"]
bindings = "pyo3"

[tool.cibuildwheel]
build = "cp312-*"
build-frontend = "build[uv]"
skip = "*-win32 *-manylinux_i686 *-musllinux*"
manylinux-x86_64-image = "manylinux_2_34"
test-groups = ["dev"]
test-sources = ["python/tests", "guppy_examples"]
test-command = "pytest python/tests"

[tool.cibuildwheel.linux.environment]
# we prepend /host to incoming paths because cibuildwheel mounts the host filesystem at /host.
# this can ONLY be done if you know for sure that the libraries available at that directory on
# the host are compatible with the build environment, e.g. manylinux compliant.
PATH = '$HOME/.cargo/bin:/host${HUGRENV_PATH}/bin:$PATH'
LLVM_SYS_211_PREFIX = '/host${HUGRENV_PATH}'
[tool.cibuildwheel.linux]
environment-pass = ["HUGRENV_PATH", "LLVM_SYS_211_PREFIX"]
before-all = [
    'dnf install libffi-devel -y',
    'curl -LO https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init',
    'curl -LO https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init.sha256',
    'sha256sum -c rustup-init.sha256',
    'chmod +x rustup-init',
    './rustup-init -y --profile minimal --default-toolchain stable --no-modify-path',
    'rustc --version',
    'curl -LO https://github.com/llvm/llvm-project/releases/download/llvmorg-14.0.6/clang+llvm-14.0.6-x86_64-linux-gnu-rhel-8.4.tar.xz',
    'mkdir -p /tmp/llvm',
    'tar xf clang+llvm-14.0.6-x86_64-linux-gnu-rhel-8.4.tar.xz -C /tmp/llvm --strip-components=1',
]
repair-wheel-command = [
    'auditwheel repair -w {dest_dir} {wheel}',
    'uvx abi3audit --strict --report {wheel}',
]

[tool.cibuildwheel.macos.environment]
PATH = '$HOME/.cargo/bin:${HUGRENV_PATH}/bin:$PATH'
LLVM_SYS_211_PREFIX = '${HUGRENV_PATH}'
MACOSX_DEPLOYMENT_TARGET = "13.2"
[tool.cibuildwheel.macos]
before-all = [
    'if [ "$(uname -m)" = "arm64" ]; then ARCH_PREFIX=arm64-apple-darwin22.3.0; else ARCH_PREFIX=x86_64-apple-darwin; fi',
    'curl -LO https://github.com/llvm/llvm-project/releases/download/llvmorg-14.0.6/clang+llvm-14.0.6-$ARCH_PREFIX.tar.xz',
    'mkdir -p /tmp/llvm',
    'tar xf clang+llvm-14.0.6-$ARCH_PREFIX.tar.xz -C /tmp/llvm --strip-components=1',
]
repair-wheel-command = [
    'DYLD_FALLBACK_LIBRARY_PATH=${HUGRENV_PATH}/lib delocate-wheel --require-archs {delocate_archs} -w {dest_dir} {wheel}',
    'uvx abi3audit --strict --report {wheel}',
]

[tool.cibuildwheel.windows.environment]
PATH = '${HUGRENV_PATH}\\bin;$PATH'
LLVM_SYS_211_PREFIX = '${HUGRENV_PATH}'
[tool.cibuildwheel.windows]
before-all = [
    'curl -LO https://github.com/PLC-lang/llvm-package-windows/releases/download/v14.0.6/LLVM-14.0.6-win64.7z',
    '7z x LLVM-14.0.6-win64.7z "-oC:\LLVM" -y',
]
before-build = ['uv pip install delvewheel']
repair-wheel-command = [
    'delvewheel repair -w {dest_dir} {wheel}',
    'uvx abi3audit --strict --report {wheel}',
]
test-groups = []
before-test = ['uv pip install --group {project}/pyproject.toml:dev']
