#!/usr/bin/env python

import sys
from utils import load_py_module_from_path



if __name__ == "__main__":
    try:
        guppy_file = sys.argv[1]
    except IndexError:
        print("Missing guppy file input argument")
        guppy_file = None

    if guppy_file:
        guppy_example = load_py_module_from_path("guppy_example_mod", str(guppy_file))
        hugr_package = guppy_example.main.compile()
        sys.stdout.buffer.write(hugr_package.to_bytes())
