name: Build/Publish python wheels

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  merge_group:
    types: [ checks_requested ]
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: read

jobs:
  job-logic:
    name: Determine job logic
    runs-on: ubuntu-latest
    outputs:
      has-changes: ${{ github.ref_name == github.event.repository.default_branch || steps.filter.outputs.build-wheels }}
      publish-release: ${{ steps.check-tag.outputs.publish_release }}
    steps:
      - uses: actions/checkout@v7
      - name: Check need release
        id: check-tag
        run: |
          echo "publish_release=$SHOULD_RELEASE" >> $GITHUB_OUTPUT
        env:
          SHOULD_RELEASE:  ${{ (github.event_name == 'release') }}
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: .github/change-filters.yml
  build_wheels:
    name: ${{ matrix.os }} wheels
    runs-on: ${{ matrix.os }}
    needs: job-logic
    if: ${{ needs.job-logic.outputs.has-changes == 'true' || needs.job-logic.outputs.publish-release == 'true' }}
    strategy:
      matrix:
        # macos-15-intel runners are x86_64
        os: [ubuntu-latest, macos-latest, macos-15-intel, windows-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v7

      - name: Set up uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          enable-cache: true

      - name: Install stable Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ runner.arch }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build wheels
        uses: pypa/cibuildwheel@v4.1

      - uses: actions/upload-artifact@v7
        with:
          name: wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
  sdist:
    needs: job-logic
    if: ${{ needs.job-logic.outputs.has-changes == 'true' || needs.job-logic.outputs.publish-release == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Build sdist
        uses: PyO3/maturin-action@v1
        with:
          command: sdist
          args: --out dist
      - name: Upload sdist
        uses: actions/upload-artifact@v7
        with:
          name: wheels-sdist
          path: dist

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build_wheels, sdist, job-logic]
    if: ${{ needs.job-logic.outputs.publish-release == 'true'}}
    steps:
      - uses: actions/download-artifact@v8
      - name: Publish to PyPI
        uses: PyO3/maturin-action@v1
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        with:
          command: upload
          args: --non-interactive --skip-existing wheels-*/*

  # This is a meta job to mark successful completion of the required checks,
  # even if they are skipped due to no changes in the relevant files.
  required-checks:
    name: Required checks build-wheels
    needs: [release, build_wheels, sdist, job-logic]
    if: ${{ !cancelled() }}
    runs-on: ubuntu-latest
    steps:
      - name: Fail if required checks failed
        # This condition should simply be `if: failure() || cancelled()`,
        # but there seems to be a bug in the github workflow runner.
        #
        # See https://github.com/orgs/community/discussions/80788
        if: |
          needs.job-logic.result == 'failure' || needs.job-logic.result == 'cancelled' ||
          needs.release.result == 'failure' || needs.release.result == 'cancelled' ||
          needs.sdist.result == 'failure' || needs.sdist.result == 'cancelled' ||
          needs.build_wheels.result == 'failure' || needs.build_wheels.result == 'cancelled'
        run: |
          echo "Required checks failed"
          echo "Please check the logs for more information"
          exit 1
      - name: Pass if required checks passed
        run: |
          echo "All required checks passed"
