name: Lint python projects

on:
  pull_request: {}
  workflow_dispatch: {}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - name: Set up uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          enable-cache: true
      - name: Install lint dependencies
        run: uv sync --frozen --group dev --no-install-project
      - name: Run prek hooks
        run: >-
          uvx prek run --all-files
          --skip cargo-fmt
          --skip cargo-check
          --skip cargo-test
          --skip cargo-clippy
          --skip cargo-doc
